package gengo

import (
	_ "embed"
	"errors"
	"fmt"
	"io"
	"iter"
	"strconv"
	"strings"

	"github.com/romshark/icumsg"
	"golang.org/x/text/language"
)

const TypePrefixCatalog = "catalog"

type Writer struct {
	w io.Writer      // Destination writer.
	l language.Tag   // Locale
	m string         // ICU message.
	t []icumsg.Token // ICU tokens.
	i int            // Current index in t.

	translatorVar string
}

var lineBreak = []byte("\n")

func (w *Writer) printf(format string, a ...any) {
	_, _ = fmt.Fprintf(w.w, format, a...)
}

func (w *Writer) print(format string) {
	_, _ = fmt.Fprint(w.w, format)
	_, _ = w.w.Write(lineBreak)
}

func (w *Writer) println(a ...any) {
	_, _ = fmt.Fprintln(w.w, a...)
}

type Message struct {
	ID        string
	TIK       string
	ICUMsg    string
	ICUTokens []icumsg.Token
}

var replacerCatalogSuffix = strings.NewReplacer("-", "_")

func LocaleToCatalogSuffix(t language.Tag) string {
	s := t.String()
	return strings.ToUpper(replacerCatalogSuffix.Replace(s))
}

//go:embed template.go.txt
var templateGoTxt string

// WritePackageBundle writes the main bundle Go file.
func (w *Writer) WritePackageBundle(
	writer io.Writer,
	packageName string,
	srcLocale language.Tag, translationLocales []language.Tag,
	headTxtLines []string,
) {
	w.w, w.l = writer, srcLocale

	w.printf("// Generated by github.com/romshark/toki. DO NOT EDIT.\n")
	for _, l := range headTxtLines {
		w.printf("// %s\n", l)
	}
	w.printf(templateGoTxt, packageName, srcLocale.String())

	w.println("// Catalogs returns an iterator over all enabled catalogs.")
	w.println("func Catalogs() iter.Seq[Reader] {")
	w.println("return func(yield func(Reader) bool) {")
	for _, l := range translationLocales {
		suffix := LocaleToCatalogSuffix(l)
		typeName := TypePrefixCatalog + suffix
		w.printf("if !yield(%s{}) { return }\n", typeName)
	}
	w.println("}}")
}

func goPlaygroundLocalesPkg(locale language.Tag) string {
	return replacerCatalogSuffix.Replace(locale.String())
}

// WritePackageCatalog writes a catalog Go file.
func (w *Writer) WritePackageCatalog(
	writer io.Writer, locale language.Tag, packageName string, headTxtLines []string,
	msgIter iter.Seq[Message],
) {
	w.w, w.l = writer, locale

	w.println("// Generated by github.com/romshark/toki. DO NOT EDIT.")
	for _, l := range headTxtLines {
		w.printf("// %s\n", l)
	}
	w.printf("\npackage %s\n", packageName)
	w.println("import (")
	w.println("\t" + `"fmt"`)
	w.println("\t" + `"io"`)
	w.println("")
	w.printf("\tlocales \"github.com/go-playground/locales\"\n")
	w.printf("\t locale \"github.com/go-playground/locales/%s\"\n",
		goPlaygroundLocalesPkg(locale))
	w.println("\tlanguage" + `"golang.org/x/text/language"`)
	w.println(")") // End of imports.

	w.writeCatalogType(msgIter)
}

func (w *Writer) writeCatalogType(msgIter iter.Seq[Message]) {
	localeCatalogSuffix := LocaleToCatalogSuffix(w.l)
	w.translatorVar = fmt.Sprintf("translator%s", localeCatalogSuffix)
	w.printf("\n// This prevents the \"imported and not used\" error " +
		"when the catalog is empty.\n")
	w.printf("var _ fmt.Formatter = nil\n")
	w.printf("\nvar locale%s language.Tag\n", localeCatalogSuffix)
	w.printf("\nvar %s = locale.New()\n", w.translatorVar)

	w.printf("func init() { locale%s = language.MustParse(%q) }\n",
		localeCatalogSuffix, w.l.String())

	// Type definition.
	catalogTypeName := TypePrefixCatalog + localeCatalogSuffix
	w.printf("type %s struct {}\n", catalogTypeName)

	// Translation functions map by TIK based on io.Writer.
	writersMapName := "writers" + localeCatalogSuffix
	w.printf(
		"var %s = map[string]func(w io.Writer, args ...any) (int, error) {\n",
		writersMapName)
	for msg := range msgIter {
		w.writeFuncIOWriter(msg.ID, msg.TIK, msg.ICUMsg, msg.ICUTokens)
	}
	w.println(`}`)

	// Method Locale.
	w.printf("func (%s) Locale() language.Tag { return locale%s }\n\n",
		catalogTypeName, localeCatalogSuffix)

	// Method Translator.
	w.printf("func (%s) Translator() locales.Translator { return %s }\n\n",
		catalogTypeName, w.translatorVar)

	// Method String.
	w.printf("func (%s) String(tik string, args ...any) string {\n",
		catalogTypeName)
	w.println(`b := poolBufGet()`)
	w.println(`defer poolBufPut(b)`)
	w.printf("f := %s[tik];\n", writersMapName)
	w.println(`if f == nil { _, _ = MissingTranslation(b, tik, args...);`)
	w.println(`} else { _, _ = f(b, args...);`)
	w.println(`}`)
	w.println(`return b.String()`)
	w.print("}\n\n")

	// Method Write.
	w.printf("func (%s) Write(\nwriter io.Writer, tik string, args ...any,\n)"+
		" (written int, err error) {\n",
		catalogTypeName)
	w.printf("f := %s[tik];\n", writersMapName)
	w.println(`if f == nil { return MissingTranslation(writer, tik, args...) }`)
	w.print("return f(writer, args...)")
	w.print("}\n\n")
}

var ErrUnsupportedArgName = errors.New("unsupported argument name")

// literalConcat returns "" if message isn't just a sequence
// of literal tokens.
func (w *Writer) literalConcat(endIndex int) string {
	l := 0
	for i := w.i; i < endIndex; i++ {
		t := w.t[i]
		switch t.Type {
		case icumsg.TokenTypeLiteral:
			l += len(t.String(w.m, w.t))
		default:
			return "" // Not a sequence of literals, abort.
		}
	}

	var s strings.Builder
	s.Grow(l)
	for i := w.i; i < endIndex; i++ {
		t := w.t[i]
		if t.Type == icumsg.TokenTypeLiteral {
			s.WriteString(t.String(w.m, w.t))
		}
	}
	return s.String()
}

type argName struct {
	Index  int
	Gender bool
}

func parseArgName(s string) (argName, error) {
	if len(s) < len("var0") || !strings.HasPrefix(s, "var") {
		return argName{}, fmt.Errorf("%w: %q", ErrUnsupportedArgName, s)
	}
	gender := strings.HasSuffix(s, "_gender")

	endIndex := len("var0")
	for i := range s[endIndex:] {
		if s[i] < '0' || s[i] > '9' {
			endIndex += i
			break
		}
	}

	v, err := strconv.ParseUint(s[len("var"):endIndex], 10, 32)
	if err != nil {
		return argName{}, err
	}
	return argName{Index: int(v), Gender: gender}, nil
}

func isTokenArgType(t icumsg.TokenType) bool {
	return t >= icumsg.TokenTypeArgTypeNumber && t <= icumsg.TokenTypeArgTypeDuration
}

func isTokenArgStyle(t icumsg.TokenType) bool {
	return t >= icumsg.TokenTypeArgStyleShort && t <= icumsg.TokenTypeArgStyleCustom
}

func iterPluralLiteralParts(s string) iter.Seq[string] {
	return func(yield func(string) bool) {
		for {
			i := strings.IndexByte(s, '#')
			if i == -1 {
				if s != "" {
					yield(s) // Yield last part.
				}
				return
			}
			if i > 0 {
				if !yield(s[:i]) { // Yield part before #.
					return
				}
			}
			if !yield("#") {
				return
			}
			s = s[i+1:] // Continue after #.
		}
	}
}
