// Code generated by github.com/romshark/datapages; DO NOT EDIT.

// Package assets provides constants for embedded static file serving.
package assets

import "path"

// URLPrefix is the URL path prefix for serving static files.
const URLPrefix = "/static/"

// Dir is the subdirectory within the embed.FS that contains the static files.
const Dir = "static"

// DevDir is the on-disk path to the static files directory for dev-mode serving.
const DevDir = "./editor/app/static"

// Path returns the URL path for a static asset file.
// For example, Path("style.css") returns "/static/style.css".
func Path(p string) string {
	return path.Join(URLPrefix, p)
}
